### ISSUE TITLE
mui@5 still advises against style-components

### ISSUE THREAD

**Issue by espretto** [SebHex/next-mui-sc-ts#1]
Hi, did you encounter any issues using the style-components' engine w/ mui for SSR? I am asking because mui@5 currently [still advises against this](https://mui.com/material-ui/guides/styled-engine/#how-to-switch-to-styled-components).

**Comment by SebHex** [comment]
@espretto I **did** encounter [CSS ordering issues](https://github.com/mui/material-ui/issues/29742) after further development upon this base
Eventually I switched from `emotion` to `styled-components` and haven't had any styling issues since

I recommend using `emotion`
